services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins:v1.0
    container_name: jenkins_ci
    ports:
      - "8080:8080"   # Puerto web de Jenkins
      - "50000:50000" # Puerto para agentes
      - "8443:8443"
    
    networks:
      - red_compartida # Nombre de la red para que pueda visualizarse entre contenedores Jenkins y postgres
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Permite a Jenkins usar Docker del host
    # environment:
    #   - JAVA_OPTS=-Djenkins.install.runSetupWizard=true //No pide contraseña
  
  
  # sonarqube:
  #   image: sonarqube:9.9.8-community
  #   container_name: sonarqube_server
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #   networks:
  #     - ci-net

volumes:
  jenkins_home:

networks: #Configuracion de la red compartida
  red_compartida:
    external: true

# Copiar los certificados SSL al contenedor
# COPY ./github.cer /usr/local/share/ca-certificates/github.crt
# COPY ./issste.gob.mx.2025.cer /usr/local/share/ca-certificates/issste.gob.mx.2025.crt


# My_CA_FWeb_Public

